# Generated by Django 3.1.2 on 2020-12-04 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='image',
            field=models.ImageField(default='', null=True, upload_to='images/', verbose_name=''),
        ),
    ]
