# Generated by Django 3.1.2 on 2021-03-26 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210326_1729'),
    ]

    operations = [

    ]
